# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2178176c5623044f07a24c564e2b2d2aeab1fec9d255620ad2d10bda2784421b98a5b18549d0d4b21a24f94cc64766940f1d249c26f0f4746da743f9232f0981

test:
  secret_key_base: ad13d32c4f9b4f30f0d9b0c5a16168e02e0c66dc272fbe2fde97fd62549ed8f7f0ae382a43bdf0fc51ad3060c2184a3c6e7ad035fefe973d0f1ca452bde1b9a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
